### ISSUE TITLE
[FAQ] How to run it on Amazon EKS ?

### ISSUE THREAD

**Issue by kirantpatil** [tzumby/rails-on-kubernetes#17]
Hi,

May I know how to run it on Amazon EKS ?

Regards,
Kiran.

**Comment by tzumby** [comment]
Hey @kirantpatil!
You can definitely deploy this with EKS. There are a few things you would need to change:

- the volume definitions (https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs, https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims)
- figure out how you will integrate with the Elastic Load Balancer (https://github.com/kubernetes-sigs/aws-load-balancer-controller)

Hope this helps.

**Comment by kirantpatil** [comment]
Found a better project. Please have a look at **_https://getkuby.io/_**
