### ISSUE TITLE
ENVs

### ISSUE THREAD

**Issue by ACPK** [tzumby/rails-on-kubernetes#4]
I noticed that the setup seems to include production ENVs in the docker-compose.yml file. What is the recommended way to handle the ENVs in your setup?

**Comment by tzumby** [comment]
Hey @ACPK, sorry for the late reply, didn't check this in a while. 

You would use a `ConfigMap` for that and [mount it in the pod](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/). If the ENV is a secret, then you can use a K8s secret and mount that as an ENV variable.
